repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: no-commit-to-branch
        args: ["--branch", "main"]
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-symlinks
      - id: check-case-conflict

  - repo: local
    hooks:
      - id: ruff-check-all
        name: ruff check (all files)
        entry: uv run ruff check . --fix
        language: system
        pass_filenames: false
        types_or: [python, pyi]

      - id: ruff-format-all
        name: ruff format (all files)
        entry: uv run ruff format .
        language: system
        pass_filenames: false
        types_or: [python, pyi]

      - id: mypy
        name: mypy
        entry: uv run mypy .
        language: system
        pass_filenames: false
        types_or: [python, pyi]
